const SKILL_ALIASES = {
  // Programming Languages
  'JavaScript': ['JavaScript', 'JS'],
  'Python': ['Python', 'Py', 'Programming in Python'],
  'Java': ['Java', 'Programming in Java'],
  'C': ['C', 'C programming language', 'Programming in C'],
  'C++': ['C++', 'Cpp', 'Programming in C++', 'Programming in Cpp'],
  'TypeScript': ['TypeScript', 'TS'],
  'Ruby': ['Ruby', 'Rails'],
  'PHP': ['PHP'],
  'Swift': ['Swift'],
  'Kotlin': ['Kotlin'],
  'Golang': ['Golang', 'Go'],
  'Rust': ['Rust'],
  'Scala': ['Scala'],
  'MATLAB': ['MATLAB'],
  'Perl': ['Perl'],
  'Haskell': ['Haskell'],
  'Lua': ['Lua'],
  'Julia': ['Julia'],
  'Next.js': ['Next.js', 'NextJS'],
  'Go': ['Go', 'Golang'],
  'R': ['R'],
  'Dart': ['Dart'],

  // Web Technologies
  'HTML': ['HTML', 'HTML5'],
  'CSS': ['CSS', 'CSS3'],
  'React': ['React', 'React.js'],
  'Angular': ['Angular', 'Angular.js'],
  'Vue.js': ['Vue.js', 'Vue'],
  'Node.js': ['Node.js', 'Node'],
  'Express.js': ['Express.js', 'Express'],
  'Django': ['Django'],
  'Flask': ['Flask'],
  'Spring Boot': ['Spring Boot', 'Spring'],
  'Laravel': ['Laravel'],
  'ASP.NET': ['ASP.NET', 'ASP'],
  'jQuery': ['jQuery'],
  'Bootstrap': ['Bootstrap'],
  'Tailwind CSS': ['Tailwind', 'Tailwind CSS'],
  'Webpack': ['Webpack'],
  'Babel': ['Babel'],
  'Redux': ['Redux'],
  'GraphQL': ['GraphQL'],
  'REST API': ['REST API', 'RESTful API'],
  'Svelte': ['Svelte'],
  'WebAssembly': ['WebAssembly', 'WASM'],
  'PWA': ['PWA', 'Progressive Web App'],
  'Jamstack': ['Jamstack'],

  // Databases
  'SQL': ['SQL'],
  'MySQL': ['MySQL'],
  'PostgreSQL': ['PostgreSQL', 'Postgres'],
  'MongoDB': ['MongoDB', 'Mongo'],
  'Redis': ['Redis'],
  'Elasticsearch': ['Elasticsearch'],
  'Cassandra': ['Cassandra'],
  'Oracle': ['Oracle'],
  'SQLite': ['SQLite'],
  'DynamoDB': ['DynamoDB'],
  'Firebase': ['Firebase'],
  'T-SQL': ['T-SQL'],
  'PL/SQL': ['PL/SQL'],

  // Data Visualization & BI Tools
  'Tableau': ['Tableau'],
  'Power BI': ['Power BI'],
  'Google Data Studio': ['Google Data Studio'],
  'Looker': ['Looker'],
  'Matplotlib': ['Matplotlib'],
  'Seaborn': ['Seaborn'],
  'D3.js': ['D3.js', 'D3'],
  'Plotly': ['Plotly'],
  'Microsoft Excel': ['Microsoft Excel', 'Excel'],
  'Google Analytics': ['Google Analytics'],
  'Kibana': ['Kibana'],

  // Data Analysis & Statistics
  'Data Analysis': ['Data Analysis'],
  'Statistical Analysis': ['Statistical Analysis'],
  'Data Modeling': ['Data Modeling'],
  'Data Mining': ['Data Mining'],
  'Predictive Analytics': ['Predictive Analytics'],
  'A/B Testing': ['A/B Testing'],
  'Data Visualization': ['Data Visualization'],
  'Business Intelligence': ['Business Intelligence', 'BI'],
  'Quantitative Analysis': ['Quantitative Analysis'],
  'Data Quality Management': ['Data Quality Management'],
  'ETL': ['ETL'],
  'Hadoop': ['Hadoop'],
  'Spark': ['Spark'],
  'Hive': ['Hive'],

  // Cloud & DevOps
  'AWS': ['AWS', 'Amazon Web Services'],
  'Azure': ['Azure'],
  'Google Cloud': ['Google Cloud', 'GCP'],
  'Docker': ['Docker'],
  'Kubernetes': ['Kubernetes'],
  'Jenkins': ['Jenkins'],
  'GitLab': ['GitLab'],
  'Terraform': ['Terraform'],
  'Ansible': ['Ansible'],
  'Prometheus': ['Prometheus'],
  'Grafana': ['Grafana'],
  'Nginx': ['Nginx'],
  'Apache': ['Apache'],
  'Serverless Computing': ['Serverless Computing'],
  'CI/CD': ['CI/CD', 'Continuous Integration', 'Continuous Deployment'],
  'CircleCI': ['CircleCI'],
  'GitHub Actions': ['GitHub Actions'],

  // AI & ML
  'Machine Learning': ['Machine Learning', 'ML'],
  'Deep Learning': ['Deep Learning'],
  'Neural Networks': ['Neural Networks'],
  'Computer Vision': ['Computer Vision'],
  'Natural Language Processing': ['Natural Language Processing', 'NLP'],
  'TensorFlow': ['TensorFlow'],
  'PyTorch': ['PyTorch'],
  'scikit-learn': ['scikit-learn'],
  'Pandas': ['Pandas'],
  'NumPy': ['NumPy'],
  'OpenCV': ['OpenCV'],
  'Hugging Face': ['Hugging Face'],
  'spaCy': ['spaCy'],
  'Reinforcement Learning': ['Reinforcement Learning'],
  'Big Data': ['Big Data'],
  'AutoML': ['AutoML'],

  // Mobile Development
  'iOS': ['iOS'],
  'Android': ['Android'],
  'React Native': ['React Native'],
  'Flutter': ['Flutter'],
  'Xamarin': ['Xamarin'],
  'Ionic': ['Ionic'],
  'SwiftUI': ['SwiftUI'],
  'Kotlin Multiplatform': ['Kotlin Multiplatform'],

  // Business & Communication Skills
  'Data Storytelling': ['Data Storytelling'],
  'Stakeholder Communication': ['Stakeholder Communication'],
  'Project Management': ['Project Management'],
  'Business Analysis': ['Business Analysis'],
  'Requirements Gathering': ['Requirements Gathering'],
  'Technical Documentation': ['Technical Documentation'],
  'Cross-functional Collaboration': ['Cross-functional Collaboration'],
  'Problem Solving': ['Problem Solving'],
  'Negotiation': ['Negotiation'],
  'Conflict Resolution': ['Conflict Resolution'],

  // Other Technical Skills
  'Git': ['Git'],
  'Github': ['Github'],
  'Linux': ['Linux'],
  'Bash': ['Bash'],
  'Agile': ['Agile'],
  'Scrum': ['Scrum'],
  'Jira': ['Jira'],
  'Confluence': ['Confluence'],
  'CI/CD': ['CI/CD', 'Continuous Integration', 'Continuous Deployment'],
  'Unit Testing': ['Unit Testing'],
  'Selenium': ['Selenium'],
  'Jest': ['Jest'],
  'Cypress': ['Cypress'],
  'Blockchain': ['Blockchain'],
  'Solidity': ['Solidity'],
  'Ethereum': ['Ethereum'],
  'Docker Swarm': ['Docker Swarm'],
  'Apache Kafka': ['Apache Kafka'],
  'Networking': ['Networking'],
  'Version Control': ['Version Control'],
};

module.exports = 
{
  SKILL_ALIASES
}